package com.qb.ad.impl;

import com.qb.ad.util.HttpGG;
import com.qb.ad.entity.DataTest;
/**
 * 创建计划方法
 */
public class CreateAdPlan {
    
    //创建计划
    public static String createAdPlan(String parkids_id, String traffic_id, String scheduleType, String cityIds) throws Exception {

        switch (scheduleType) {
            case "0": //独占
//                String cityIds ="3";
                String AdPlanIndependent1 = "{\"adsensePositionId\":1,\"advertiserId\":" + DataTest.advertiserId + ",\"autoFill\":1,\"checkAllData\":false,\"cityIds\":[" + cityIds + "],\"comment\":\"创建独占广告计划入场推送备注1\",\"content\":\"文案：独占-1入场\",\"endTime\":" + DataTest.endTime + ",\"imageUri\":\"\",\"industryId\":7,\"isApi\":0,\"isRedirect\":0,\"isSubstitution\":0,\"matchCondition\":[0,0,0,0],\"mediaType\":1,\"name\":\"" + DataTest.createAdvertiseName + "_1" + "\",\"parkIds\":[2147483647," + parkids_id + "],\"parkTypeIds\":[2147483647,0],\"price\":" + DataTest.Indep_price[0] + ",\"priceTotal\":" + DataTest.Indep_priceTotal[0] + ",\"priceType\":" + DataTest.Indep_priceType[0] + ",\"publishTimeList\":[],\"scheduleIntervalType\":0,\"scheduleType\":0,\"startTime\":" + DataTest.startTime + ",\"target\":" + DataTest.Indep_target[0] + ",\"timeLimit\":0,\"trafficIds\":[" + traffic_id + "],\"url\":\"" + DataTest.url[0] + "\"}";
                String AdPlanIndependent2 = "{\"adsensePositionId\":2,\"advertiserId\":" + DataTest.advertiserId + ",\"autoFill\":1,\"checkAllData\":false,\"cityIds\":[" + cityIds + "],\"comment\":\"创建独占广告计划出场推送备注2\",\"content\":\"文案：独占-2出场\",\"endTime\":" + DataTest.endTime + ",\"imageUri\":\"\",\"industryId\":1,\"isApi\":0,\"isRedirect\":0,\"isSubstitution\":1,\"matchCondition\":[0,0,0,0],\"mediaType\":0,\"name\":\"" + DataTest.createAdvertiseName + "_2" + "\",\"parkIds\":[2147483647," + parkids_id + "],\"parkTypeIds\":[2147483647,0],\"price\":" + DataTest.Indep_price[1] + ",\"priceTotal\":" + DataTest.Indep_priceTotal[1] + ",\"priceType\":" + DataTest.Indep_priceType[1] + ",\"publishTimeList\":[],\"scheduleIntervalType\":0,\"scheduleType\":0,\"startTime\":" + DataTest.startTime + ",\"target\":" + DataTest.Indep_target[1] + ",\"timeLimit\":0,\"trafficIds\":[" + traffic_id + "],\"url\":\"" + DataTest.url[1] + "\"}";
                String AdPlanIndependent3 = "{\"adsensePositionId\":3,\"advertiserId\":" + DataTest.advertiserId + ",\"autoFill\":1,\"checkAllData\":false,\"cityIds\":[" + cityIds + "],\"comment\":\"创建独占广告计划输入车牌备注3\",\"content\":\"\",\"endTime\":" + DataTest.endTime + ",\"imageUri\":\"https://anbokeji.oss-cn-hangzhou.aliyuncs.com/images/20200610/127144414.jpg\",\"industryId\":2,\"isApi\":0,\"isRedirect\":0,\"isSubstitution\":0,\"matchCondition\":[0,0,0,0],\"mediaType\":1,\"name\":\"" + DataTest.createAdvertiseName + "_3" + "\",\"parkIds\":[2147483647," + parkids_id + "],\"parkTypeIds\":[2147483647,0],\"price\":" + DataTest.Indep_price[2] + ",\"priceTotal\":" + DataTest.Indep_priceTotal[2] + ",\"priceType\":" + DataTest.Indep_priceType[2] + ",\"publishTimeList\":[],\"scheduleIntervalType\":0,\"scheduleType\":0,\"startTime\":" + DataTest.startTime + ",\"target\":" + DataTest.Indep_target[2] + ",\"timeLimit\":0,\"trafficIds\":[" + traffic_id + "],\"url\":\"" + DataTest.url[2] + "\"}";
                String AdPlanIndependent4 = "{\"adsensePositionId\":4,\"advertiserId\":" + DataTest.advertiserId + ",\"autoFill\":1,\"checkAllData\":false,\"cityIds\":[" + cityIds + "],\"comment\":\"创建独占广告计划支付页面备注4\",\"content\":\"\",\"endTime\":" + DataTest.endTime + ",\"imageUri\":\"https://anbokeji.oss-cn-hangzhou.aliyuncs.com/images/20200610/233150047.jpg\",\"industryId\":3,\"isApi\":0,\"isRedirect\":0,\"isSubstitution\":1,\"matchCondition\":[0,0,0,0],\"mediaType\":3,\"appId\":\"wxc3b7d3c12886ade8\",\"name\":\"" + DataTest.createAdvertiseName + "_4" + "\",\"parkIds\":[2147483647," + parkids_id + "],\"parkTypeIds\":[2147483647,0],\"price\":" + DataTest.Indep_price[3] + ",\"priceTotal\":" + DataTest.Indep_priceTotal[3] + ",\"priceType\":" + DataTest.Indep_priceType[3] + ",\"publishTimeList\":[],\"scheduleIntervalType\":0,\"scheduleType\":0,\"startTime\":" + DataTest.startTime + ",\"target\":" + DataTest.Indep_target[3] + ",\"timeLimit\":0,\"trafficIds\":[" + traffic_id + "],\"url\":\"" + DataTest.url[3] + "\"}";
                String AdPlanIndependent5 = "{\"adsensePositionId\":5,\"advertiserId\":" + DataTest.advertiserId + ",\"autoFill\":1,\"checkAllData\":false,\"cityIds\":[" + cityIds + "],\"comment\":\"创建独占广告计划付款成功备注5\",\"content\":\"\",\"endTime\":" + DataTest.endTime + ",\"imageUri\":\"https://anbokeji.oss-cn-hangzhou.aliyuncs.com/images/20200610/351145032.jpg\",\"industryId\":4,\"isApi\":0,\"isRedirect\":0,\"isSubstitution\":0,\"matchCondition\":[0,0,0,0],\"mediaType\":2,\"name\":\"" + DataTest.createAdvertiseName + "_5" + "\",\"parkIds\":[2147483647," + parkids_id + "],\"parkTypeIds\":[2147483647,0],\"price\":" + DataTest.Indep_price[4] + ",\"priceTotal\":" + DataTest.Indep_priceTotal[4] + ",\"priceType\":" + DataTest.Indep_priceType[4] + ",\"scheduleIntervalType\":0,\"publishTimeList\":[],\"scheduleType\":0,\"startTime\":" + DataTest.startTime + ",\"target\":" + DataTest.Indep_target[4] + ",\"timeLimit\":0,\"trafficIds\":[" + traffic_id + "],\"url\":\"" + DataTest.url[4] + "\"}";
                HttpGG.doPost2( DataTest.plan_create_url, AdPlanIndependent1, DataTest.Access_Token );
                HttpGG.doPost2( DataTest.plan_create_url, AdPlanIndependent2, DataTest.Access_Token );
                HttpGG.doPost2( DataTest.plan_create_url, AdPlanIndependent3, DataTest.Access_Token );
                HttpGG.doPost2( DataTest.plan_create_url, AdPlanIndependent4, DataTest.Access_Token );
                HttpGG.doPost2( DataTest.plan_create_url, AdPlanIndependent5, DataTest.Access_Token );
                break;
            case "1": //共享
                String AdPlanShare1 = "{\"adsensePositionId\":1,\"advertiserId\":" + DataTest.advertiserId + ",\"ceilingCntDaily\":" + DataTest.ceilingCntDaily[0] + ",\"checkAllData\":false,\"cityIds\":[" + cityIds + "],\"comment\":\"" + "创建共享广告计划入场推送备注1" + "\",\"content\":\"" + DataTest.createAdvertiseName + "测试进场\",\"endTime\":" + DataTest.endTime + ",\"imageUri\":\"\",\"industryId\":3,\"isRedirect\":0,\"mediaType\":0,\"name\":\"" + DataTest.createAdvertiseName + "_1" + "\",\"parkIds\":[2147483647," + parkids_id + "],\"parkTypeIds\":[2147483647,0],\"price\":" + DataTest.Share_price[0] + ",\"priceTotal\":28,\"priceType\":" + DataTest.Share_priceType[0] + ",\"scheduleIntervalCnt\":" + DataTest.Share_scheduleIntervalCnt[0] + ",\"scheduleIntervalHours\":" + DataTest.Share_scheduleIntervalHours[0] + ",\"scheduleIntervalType\":" + DataTest.Share_scheduleIntervalType[0] + ",\"scheduleType\":1,\"startTime\":" + DataTest.startTime + ",\"target\":" + DataTest.Share_target[0] + ",\"trafficIds\":[" + traffic_id + "],\"url\":\"" + DataTest.url[0] + "\",\"weight\":1}";
                String AdPlanShare2 = "{\"adsensePositionId\":2,\"advertiserId\":" + DataTest.advertiserId + ",\"ceilingCntDaily\":" + DataTest.ceilingCntDaily[1] + ",\"checkAllData\":false,\"cityIds\":[" + cityIds + "],\"comment\":\"" + "创建共享广告计划出场推送备注2" + "\",\"content\":\"" + DataTest.createAdvertiseName + "测试出场\",\"endTime\":" + DataTest.endTime + ",\"imageUri\":\"\",\"industryId\":6,\"isRedirect\":0,\"mediaType\":1,\"name\":\"" + DataTest.createAdvertiseName + "_2" + "\",\"parkIds\":[2147483647," + parkids_id + "],\"parkTypeIds\":[2147483647,0],\"price\":" + DataTest.Share_price[1] + ",\"priceTotal\":40,\"priceType\":" + DataTest.Share_priceType[1] + ",\"scheduleIntervalCnt\":" + DataTest.Share_scheduleIntervalCnt[1] + ",\"scheduleIntervalHours\":" + DataTest.Share_scheduleIntervalHours[1] + ",\"scheduleIntervalType\":" + DataTest.Share_scheduleIntervalType[1] + ",\"scheduleType\":1,\"startTime\":" + DataTest.startTime + ",\"target\":" + DataTest.Share_target[1] + ",\"trafficIds\":[" + traffic_id + "],\"url\":\"" + DataTest.url[1] + "\",\"weight\":2}";
                String AdPlanShare3 = "{\"adsensePositionId\":3,\"advertiserId\":" + DataTest.advertiserId + ",\"ceilingCntDaily\":" + DataTest.ceilingCntDaily[2] + ",\"checkAllData\":false,\"cityIds\":[" + cityIds + "],\"comment\":\"" + "创建共享广告计划输入车牌备注3" + "\",\"content\":\"\",\"endTime\":" + DataTest.endTime + ",\"imageUri\":\"" + DataTest.imageUri_3 + "\",\"industryId\":6,\"isRedirect\":0,\"mediaType\":1,\"name\":\"" + DataTest.createAdvertiseName + "_3" + "\",\"parkIds\":[2147483647," + parkids_id + "],\"parkTypeIds\":[2147483647,0],\"price\":" + DataTest.Share_price[2] + ",\"priceTotal\":30000,\"priceType\":" + DataTest.Share_priceType[2] + ",\"scheduleIntervalCnt\":" + DataTest.Share_scheduleIntervalCnt[2] + ",\"scheduleIntervalHours\":" + DataTest.Share_scheduleIntervalHours[2] + ",\"scheduleIntervalType\":" + DataTest.Share_scheduleIntervalType[2] + ",\"scheduleType\":1,\"startTime\":" + DataTest.startTime + ",\"target\":" + DataTest.Share_target[2] + ",\"trafficIds\":[" + traffic_id + "],\"url\":\"" + DataTest.url[2] + "\",\"weight\":2}";
                String AdPlanShare4 = "{\"adsensePositionId\":4,\"advertiserId\":" + DataTest.advertiserId + ",\"ceilingCntDaily\":" + DataTest.ceilingCntDaily[3] + ",\"checkAllData\":false,\"cityIds\":[" + cityIds + "],\"comment\":\"" + "创建共享广告计划支付页面备注4" + "\",\"content\":\"\",\"endTime\":" + DataTest.endTime + ",\"imageUri\":\"" + DataTest.imageUri_4 + "\",\"industryId\":55,\"industryName\":\"测试广告内容-其他\",\"isRedirect\":0,\"mediaType\":3,\"appId\":\"wxc3b7d3c12886ade8\",\"name\":\"" + DataTest.createAdvertiseName + "_4" + "\",\"parkIds\":[2147483647," + parkids_id + "],\"parkTypeIds\":[2147483647,0],\"price\":" + DataTest.Share_priceType[3] + ",\"priceTotal\":120,\"priceType\":" + DataTest.Share_priceType[3] + ",\"scheduleIntervalCnt\":" + DataTest.Share_scheduleIntervalCnt[3] + ",\"scheduleIntervalHours\":" + DataTest.Share_scheduleIntervalHours[3] + ",\"scheduleIntervalType\":" + DataTest.Share_scheduleIntervalType[3] + ",\"scheduleType\":1,\"startTime\":" + DataTest.startTime + ",\"target\":" + DataTest.Share_target[3] + ",\"trafficIds\":[" + traffic_id + "],\"url\":\"" + DataTest.url[3] + "\",\"weight\":4}";
                String AdPlanShare5 = "{\"adsensePositionId\":5,\"advertiserId\":" + DataTest.advertiserId + ",\"ceilingCntDaily\":" + DataTest.ceilingCntDaily[4] + ",\"checkAllData\":false,\"cityIds\":[" + cityIds + "],\"comment\":\"" + "创建共享广告计划付款成功备注5" + "\",\"content\":\"\",\"endTime\":" + DataTest.endTime + ",\"imageUri\":\"" + DataTest.imageUri_5 + "\",\"industryId\":7,\"isRedirect\":0,\"mediaType\":2,\"name\":\"" + DataTest.createAdvertiseName + "_5" + "\",\"parkIds\":[" + parkids_id + "],\"parkTypeIds\":[2147483647,0],\"price\":" + DataTest.Share_price[4] + ",\"priceTotal\":64130,\"priceType\":" + DataTest.Share_priceType[4] + ",\"scheduleIntervalCnt\":" + DataTest.Share_scheduleIntervalCnt[4] + ",\"scheduleIntervalHours\":" + DataTest.Share_scheduleIntervalHours[4] + ",\"scheduleIntervalType\":" + DataTest.Share_scheduleIntervalType[4] + ",\"scheduleType\":1,\"startTime\":" + DataTest.startTime + ",\"target\":" + DataTest.Share_target[3] + ",\"trafficIds\":[" + traffic_id + "],\"url\":\"" + DataTest.url[4] + "\",\"weight\":5}";
                HttpGG.doPost2( DataTest.plan_create_url, AdPlanShare1, DataTest.Access_Token );
                HttpGG.doPost2( DataTest.plan_create_url, AdPlanShare2, DataTest.Access_Token );
                HttpGG.doPost2( DataTest.plan_create_url, AdPlanShare3, DataTest.Access_Token );
                HttpGG.doPost2( DataTest.plan_create_url, AdPlanShare4, DataTest.Access_Token );
                HttpGG.doPost2( DataTest.plan_create_url, AdPlanShare5, DataTest.Access_Token );
                break;
            case "2":
                String AdPlanMixture1_1 = "{\"adsensePositionId\":1,\"advertiserId\":" + DataTest.advertiserId + ",\"ceilingCntDaily\":100,\"checkAllData\":false,\"cityIds\":[" + cityIds + "],\"comment\":\"" + "创建共享广告计划入场推送备注1" + "\",\"content\":\"" + DataTest.createAdvertiseName + "测试进场\",\"endTime\":" + DataTest.endTime + ",\"imageUri\":\"\",\"industryId\":3,\"isRedirect\":0,\"mediaType\":0,\"name\":\"" + DataTest.createAdvertiseName + "_1" + "\",\"parkIds\":[2147483647," + parkids_id + "],\"parkTypeIds\":[2147483647,0],\"price\":" + DataTest.Share_price[0] + ",\"priceTotal\":28,\"priceType\":" + DataTest.Share_priceType[0] + ",\"scheduleIntervalCnt\":" + DataTest.Share_scheduleIntervalCnt[0] + ",\"scheduleIntervalHours\":" + DataTest.Share_scheduleIntervalHours[0] + ",\"scheduleIntervalType\":" + DataTest.Share_scheduleIntervalType[0] + ",\"scheduleType\":1,\"startTime\":" + DataTest.startTime + ",\"target\":" + DataTest.Share_target[0] + ",\"trafficIds\":[" + traffic_id + "],\"url\":\"" + DataTest.url[0] + "\",\"weight\":1}";
                String AdPlanMixture1_2 = "{\"adsensePositionId\":1,\"advertiserId\":" + DataTest.advertiserId + ",\"ceilingCntDaily\":100,\"checkAllData\":false,\"cityIds\":[" + cityIds + "],\"comment\":\"" + "创建共享广告计划入场推送备注1" + "\",\"content\":\"" + DataTest.createAdvertiseName + "测试进场\",\"endTime\":" + DataTest.endTime + ",\"imageUri\":\"\",\"industryId\":3,\"isRedirect\":0,\"mediaType\":0,\"name\":\"" + DataTest.createAdvertiseName + "_1" + "\",\"parkIds\":[2147483647," + parkids_id + "],\"parkTypeIds\":[2147483647,0],\"price\":" + DataTest.Share_price[0] + ",\"priceTotal\":28,\"priceType\":" + DataTest.Share_priceType[0] + ",\"scheduleIntervalCnt\":" + DataTest.Share_scheduleIntervalCnt[0] + ",\"scheduleIntervalHours\":" + DataTest.Share_scheduleIntervalHours[0] + ",\"scheduleIntervalType\":" + DataTest.Share_scheduleIntervalType[0] + ",\"scheduleType\":1,\"startTime\":" + DataTest.startTime + ",\"target\":" + DataTest.Share_target[0] + ",\"trafficIds\":[" + traffic_id + "],\"url\":\"" + DataTest.url[0] + "\",\"weight\":1}";
                String AdPlanMixture2 = "{\"adsensePositionId\":2,\"advertiserId\":" + DataTest.advertiserId + ",\"checkAllData\":false,\"cityIds\":[" + cityIds + "],\"comment\":\"创建独占广告计划出场推送备注2\",\"content\":\"文案：独占-2出场\",\"endTime\":" + DataTest.endTime + ",\"imageUri\":\"\",\"industryId\":1,\"isRedirect\":0,\"isSubstitution\":1,\"mediaType\":0,\"name\":\"" + DataTest.createAdvertiseName + "_2" + "\",\"parkIds\":[2147483647," + parkids_id + "],\"parkTypeIds\":[2147483647,0],\"price\":" + DataTest.Indep_price[1] + ",\"priceTotal\":" + DataTest.Indep_priceTotal[1] + ",\"priceType\":" + DataTest.Indep_priceType[1] + ",\"scheduleIntervalType\":0,\"scheduleType\":0,\"startTime\":" + DataTest.startTime + ",\"target\":" + DataTest.Indep_target[1] + ",\"trafficIds\":[" + traffic_id + "],\"url\":\"" + DataTest.url[1] + "\"}";
                String AdPlanMixture3 = "{\"adsensePositionId\":3,\"advertiserId\":" + DataTest.advertiserId + ",\"checkAllData\":false,\"cityIds\":[" + cityIds + "],\"comment\":\"创建独占广告计划输入车牌备注3\",\"content\":\"\",\"endTime\":" + DataTest.endTime + ",\"imageUri\":\"https://anbokeji.oss-cn-hangzhou.aliyuncs.com/images/20200610/127144414.jpg\",\"industryId\":2,\"isRedirect\":0,\"isSubstitution\":0,\"mediaType\":1,\"name\":\"" + DataTest.createAdvertiseName + "_3" + "\",\"parkIds\":[2147483647," + parkids_id + "],\"parkTypeIds\":[2147483647,0],\"price\":" + DataTest.Indep_price[2] + ",\"priceTotal\":" + DataTest.Indep_priceTotal[2] + ",\"priceType\":" + DataTest.Indep_priceType[2] + ",\"scheduleIntervalType\":0,\"scheduleType\":0,\"startTime\":" + DataTest.startTime + ",\"target\":" + DataTest.Indep_target[2] + ",\"trafficIds\":[" + traffic_id + "],\"url\":\"" + DataTest.url[2] + "\"}";
                String AdPlanMixture4_1 = "{\"adsensePositionId\":4,\"advertiserId\":" + DataTest.advertiserId + ",\"ceilingCntDaily\":400,\"checkAllData\":false,\"cityIds\":[" + cityIds + "],\"comment\":\"" + "创建共享广告计划支付页面备注4" + "\",\"content\":\"\",\"endTime\":" + DataTest.endTime + ",\"imageUri\":\"" + DataTest.imageUri_4 + "\",\"industryId\":55,\"industryName\":\"测试广告内容-其他\",\"isRedirect\":0,\"mediaType\":3,\"appId\":\"wxc3b7d3c12886ade8\",\"name\":\"" + DataTest.createAdvertiseName + "_4" + "\",\"parkIds\":[2147483647," + parkids_id + "],\"parkTypeIds\":[2147483647,0],\"price\":" + DataTest.Share_priceType[3] + ",\"priceTotal\":120,\"priceType\":" + DataTest.Share_priceType[3] + ",\"scheduleIntervalCnt\":" + DataTest.Share_scheduleIntervalCnt[3] + ",\"scheduleIntervalHours\":" + DataTest.Share_scheduleIntervalHours[3] + ",\"scheduleIntervalType\":" + DataTest.Share_scheduleIntervalType[3] + ",\"scheduleType\":1,\"startTime\":" + DataTest.startTime + ",\"target\":" + DataTest.Share_target[3] + ",\"trafficIds\":[" + traffic_id + "],\"url\":\"" + DataTest.url[3] + "\",\"weight\":4}";
                String AdPlanMixture4_2 = "{\"adsensePositionId\":4,\"advertiserId\":" + DataTest.advertiserId + ",\"ceilingCntDaily\":400,\"checkAllData\":false,\"cityIds\":[" + cityIds + "],\"comment\":\"" + "创建共享广告计划支付页面备注4" + "\",\"content\":\"\",\"endTime\":" + DataTest.endTime + ",\"imageUri\":\"" + DataTest.imageUri_4 + "\",\"industryId\":55,\"industryName\":\"测试广告内容-其他\",\"isRedirect\":0,\"mediaType\":3,\"appId\":\"wxc3b7d3c12886ade8\",\"name\":\"" + DataTest.createAdvertiseName + "_4" + "\",\"parkIds\":[2147483647," + parkids_id + "],\"parkTypeIds\":[2147483647,0],\"price\":" + DataTest.Share_priceType[3] + ",\"priceTotal\":120,\"priceType\":" + DataTest.Share_priceType[3] + ",\"scheduleIntervalCnt\":" + DataTest.Share_scheduleIntervalCnt[3] + ",\"scheduleIntervalHours\":" + DataTest.Share_scheduleIntervalHours[3] + ",\"scheduleIntervalType\":" + DataTest.Share_scheduleIntervalType[3] + ",\"scheduleType\":1,\"startTime\":" + DataTest.startTime + ",\"target\":" + DataTest.Share_target[3] + ",\"trafficIds\":[" + traffic_id + "],\"url\":\"" + DataTest.url[3] + "\",\"weight\":4}";
                String AdPlanMixture5 = "{\"adsensePositionId\":5,\"advertiserId\":" + DataTest.advertiserId + ",\"checkAllData\":false,\"cityIds\":[" + cityIds + "],\"comment\":\"创建独占广告计划付款成功备注5\",\"content\":\"\",\"endTime\":" + DataTest.endTime + ",\"imageUri\":\"https://anbokeji.oss-cn-hangzhou.aliyuncs.com/images/20200610/351145032.jpg\",\"industryId\":4,\"isRedirect\":0,\"isSubstitution\":0,\"mediaType\":2,\"name\":\"" + DataTest.createAdvertiseName + "_5" + "\",\"parkIds\":[2147483647," + parkids_id + "],\"parkTypeIds\":[2147483647,0],\"price\":" + DataTest.Indep_price[4] + ",\"priceTotal\":" + DataTest.Indep_priceTotal[4] + ",\"priceType\":" + DataTest.Indep_priceType[4] + ",\"scheduleIntervalType\":0,\"scheduleType\":0,\"startTime\":" + DataTest.startTime + ",\"target\":" + DataTest.Indep_target[4] + ",\"trafficIds\":[" + traffic_id + "],\"url\":\"" + DataTest.url[4] + "\"}";
                HttpGG.doPost2( DataTest.plan_create_url, AdPlanMixture1_1, DataTest.Access_Token );
                HttpGG.doPost2( DataTest.plan_create_url, AdPlanMixture1_2, DataTest.Access_Token );
                HttpGG.doPost2( DataTest.plan_create_url, AdPlanMixture2, DataTest.Access_Token );
                HttpGG.doPost2( DataTest.plan_create_url, AdPlanMixture3, DataTest.Access_Token );
                HttpGG.doPost2( DataTest.plan_create_url, AdPlanMixture4_1, DataTest.Access_Token );
                HttpGG.doPost2( DataTest.plan_create_url, AdPlanMixture4_2, DataTest.Access_Token );
                HttpGG.doPost2( DataTest.plan_create_url, AdPlanMixture5, DataTest.Access_Token );

            default:
//        System.out.println("计划结果 ： " + AdPlanShareResponse);
        }

        return null;
    }
}
